[advisories]
unmaintained = "deny"
vulnerability = "deny"
unsound = "deny"
yanked = "deny"
ignore = [
]

[bans]
multiple-versions = "deny"

[licenses]
unlicensed = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "MIT",
]
