[advisories]
yanked = "deny"
ignore = [
]

[bans]
multiple-versions = "deny"

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "MIT",
]
