/// Pairs an invalid license identifier with its valid SPDX license identifier.
/// These invalid identifiers are only allowed when using `Lax` parsing.
pub const IMPRECISE_NAMES: &[(&str, &str)] = &[
    ("agplv3", "AGPL-3.0"),
    ("agpl", "AGPL-3.0"),
    ("apache 2.0", "Apache-2.0"),
    ("apache-2", "Apache-2.0"),
    ("apache2", "Apache-2.0"),
    ("apache", "Apache-2.0"),
    ("asl2.0", "Apache-2.0"),
    ("bsd 2-clause", "BSD-2-Clause"),
    ("bsd-2clause", "BSD-2-Clause"),
    ("bsd3", "BSD-3-Clause"),
    ("bsd", "BSD-2-Clause"),
    ("cc0", "CC0-1.0"),
    ("gnu gpl v2", "GPL-3.0-only"),
    ("gnu gpl v3", "GPL-3.0-only"),
    ("gpl v2", "GPL-2.0-only"),
    ("gpl v3", "GPL-3.0-only"),
    ("gpl-1.0", "GPL-1.0-only"),
    ("gpl-2.0", "GPL-2.0-only"),
    ("gpl-3.0", "GPL-3.0-only"),
    ("gpl2", "GPL-2.0-only"),
    ("gpl3", "GPL-3.0-only"),
    ("gplv2", "GPL-2.0-only"),
    ("gplv3", "GPL-3.0-only"),
    ("gpl", "GPL-2.0-only"),
    ("lgpl", "LGPL-2.0-only"),
    ("GPL-1.0", "GPL-1.0-only"),
    ("GPL-2.0", "GPL-2.0-only"),
    ("GPL-3.0", "GPL-3.0-only"),
    ("mit", "MIT"),
    ("mpl2", "MPL-2.0"),
    ("mpl", "MPL-2.0"),
    ("simplified bsd license", "BSD-2-Clause"),
    ("zlib", "Zlib"),
];
