[package]
name = "update"
version = "0.1.0"
authors = ["Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
publish = false

[dependencies]
failure = "0.1.5"
reqwest = { version = "0.9.20", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.40"
