pub const LICENSE_TEXTS: &[(&str, &str)] = &[
    ("0BSD", include!("text/0BSD")),
    ("AAL", include!("text/AAL")),
    ("ADSL", include!("text/ADSL")),
    ("AFL-1.1", include!("text/AFL-1.1")),
    ("AFL-1.2", include!("text/AFL-1.2")),
    ("AFL-2.0", include!("text/AFL-2.0")),
    ("AFL-2.1", include!("text/AFL-2.1")),
    ("AFL-3.0", include!("text/AFL-3.0")),
    ("AGPL-1.0", include!("text/AGPL-1.0")),
    ("AGPL-1.0-only", include!("text/AGPL-1.0-only")),
    ("AGPL-1.0-or-later", include!("text/AGPL-1.0-or-later")),
    ("AGPL-3.0", include!("text/AGPL-3.0")),
    ("AGPL-3.0-only", include!("text/AGPL-3.0-only")),
    ("AGPL-3.0-or-later", include!("text/AGPL-3.0-or-later")),
    ("AMDPLPA", include!("text/AMDPLPA")),
    ("AML", include!("text/AML")),
    ("AMPAS", include!("text/AMPAS")),
    ("ANTLR-PD", include!("text/ANTLR-PD")),
    ("ANTLR-PD-fallback", include!("text/ANTLR-PD-fallback")),
    ("APAFML", include!("text/APAFML")),
    ("APL-1.0", include!("text/APL-1.0")),
    ("APSL-1.0", include!("text/APSL-1.0")),
    ("APSL-1.1", include!("text/APSL-1.1")),
    ("APSL-1.2", include!("text/APSL-1.2")),
    ("APSL-2.0", include!("text/APSL-2.0")),
    ("Abstyles", include!("text/Abstyles")),
    ("Adobe-2006", include!("text/Adobe-2006")),
    ("Adobe-Glyph", include!("text/Adobe-Glyph")),
    ("Afmparse", include!("text/Afmparse")),
    ("Aladdin", include!("text/Aladdin")),
    ("Apache-1.0", include!("text/Apache-1.0")),
    ("Apache-1.1", include!("text/Apache-1.1")),
    ("Apache-2.0", include!("text/Apache-2.0")),
    ("Artistic-1.0", include!("text/Artistic-1.0")),
    ("Artistic-1.0-Perl", include!("text/Artistic-1.0-Perl")),
    ("Artistic-1.0-cl8", include!("text/Artistic-1.0-cl8")),
    ("Artistic-2.0", include!("text/Artistic-2.0")),
    ("BSD-1-Clause", include!("text/BSD-1-Clause")),
    ("BSD-2-Clause", include!("text/BSD-2-Clause")),
    (
        "BSD-2-Clause-FreeBSD",
        include!("text/BSD-2-Clause-FreeBSD"),
    ),
    ("BSD-2-Clause-NetBSD", include!("text/BSD-2-Clause-NetBSD")),
    ("BSD-2-Clause-Patent", include!("text/BSD-2-Clause-Patent")),
    ("BSD-2-Clause-Views", include!("text/BSD-2-Clause-Views")),
    ("BSD-3-Clause", include!("text/BSD-3-Clause")),
    (
        "BSD-3-Clause-Attribution",
        include!("text/BSD-3-Clause-Attribution"),
    ),
    ("BSD-3-Clause-Clear", include!("text/BSD-3-Clause-Clear")),
    ("BSD-3-Clause-LBNL", include!("text/BSD-3-Clause-LBNL")),
    (
        "BSD-3-Clause-Modification",
        include!("text/BSD-3-Clause-Modification"),
    ),
    (
        "BSD-3-Clause-No-Military-License",
        include!("text/BSD-3-Clause-No-Military-License"),
    ),
    (
        "BSD-3-Clause-No-Nuclear-License",
        include!("text/BSD-3-Clause-No-Nuclear-License"),
    ),
    (
        "BSD-3-Clause-No-Nuclear-License-2014",
        include!("text/BSD-3-Clause-No-Nuclear-License-2014"),
    ),
    (
        "BSD-3-Clause-No-Nuclear-Warranty",
        include!("text/BSD-3-Clause-No-Nuclear-Warranty"),
    ),
    (
        "BSD-3-Clause-Open-MPI",
        include!("text/BSD-3-Clause-Open-MPI"),
    ),
    ("BSD-4-Clause", include!("text/BSD-4-Clause")),
    (
        "BSD-4-Clause-Shortened",
        include!("text/BSD-4-Clause-Shortened"),
    ),
    ("BSD-4-Clause-UC", include!("text/BSD-4-Clause-UC")),
    ("BSD-Protection", include!("text/BSD-Protection")),
    ("BSD-Source-Code", include!("text/BSD-Source-Code")),
    ("BSL-1.0", include!("text/BSL-1.0")),
    ("BUSL-1.1", include!("text/BUSL-1.1")),
    ("Bahyph", include!("text/Bahyph")),
    ("Barr", include!("text/Barr")),
    ("Beerware", include!("text/Beerware")),
    ("BitTorrent-1.0", include!("text/BitTorrent-1.0")),
    ("BitTorrent-1.1", include!("text/BitTorrent-1.1")),
    ("BlueOak-1.0.0", include!("text/BlueOak-1.0.0")),
    ("Borceux", include!("text/Borceux")),
    ("C-UDA-1.0", include!("text/C-UDA-1.0")),
    ("CAL-1.0", include!("text/CAL-1.0")),
    (
        "CAL-1.0-Combined-Work-Exception",
        include!("text/CAL-1.0-Combined-Work-Exception"),
    ),
    ("CATOSL-1.1", include!("text/CATOSL-1.1")),
    ("CC-BY-1.0", include!("text/CC-BY-1.0")),
    ("CC-BY-2.0", include!("text/CC-BY-2.0")),
    ("CC-BY-2.5", include!("text/CC-BY-2.5")),
    ("CC-BY-2.5-AU", include!("text/CC-BY-2.5-AU")),
    ("CC-BY-3.0", include!("text/CC-BY-3.0")),
    ("CC-BY-3.0-AT", include!("text/CC-BY-3.0-AT")),
    ("CC-BY-3.0-DE", include!("text/CC-BY-3.0-DE")),
    ("CC-BY-3.0-NL", include!("text/CC-BY-3.0-NL")),
    ("CC-BY-3.0-US", include!("text/CC-BY-3.0-US")),
    ("CC-BY-4.0", include!("text/CC-BY-4.0")),
    ("CC-BY-NC-1.0", include!("text/CC-BY-NC-1.0")),
    ("CC-BY-NC-2.0", include!("text/CC-BY-NC-2.0")),
    ("CC-BY-NC-2.5", include!("text/CC-BY-NC-2.5")),
    ("CC-BY-NC-3.0", include!("text/CC-BY-NC-3.0")),
    ("CC-BY-NC-3.0-DE", include!("text/CC-BY-NC-3.0-DE")),
    ("CC-BY-NC-4.0", include!("text/CC-BY-NC-4.0")),
    ("CC-BY-NC-ND-1.0", include!("text/CC-BY-NC-ND-1.0")),
    ("CC-BY-NC-ND-2.0", include!("text/CC-BY-NC-ND-2.0")),
    ("CC-BY-NC-ND-2.5", include!("text/CC-BY-NC-ND-2.5")),
    ("CC-BY-NC-ND-3.0", include!("text/CC-BY-NC-ND-3.0")),
    ("CC-BY-NC-ND-3.0-DE", include!("text/CC-BY-NC-ND-3.0-DE")),
    ("CC-BY-NC-ND-3.0-IGO", include!("text/CC-BY-NC-ND-3.0-IGO")),
    ("CC-BY-NC-ND-4.0", include!("text/CC-BY-NC-ND-4.0")),
    ("CC-BY-NC-SA-1.0", include!("text/CC-BY-NC-SA-1.0")),
    ("CC-BY-NC-SA-2.0", include!("text/CC-BY-NC-SA-2.0")),
    ("CC-BY-NC-SA-2.0-FR", include!("text/CC-BY-NC-SA-2.0-FR")),
    ("CC-BY-NC-SA-2.0-UK", include!("text/CC-BY-NC-SA-2.0-UK")),
    ("CC-BY-NC-SA-2.5", include!("text/CC-BY-NC-SA-2.5")),
    ("CC-BY-NC-SA-3.0", include!("text/CC-BY-NC-SA-3.0")),
    ("CC-BY-NC-SA-3.0-DE", include!("text/CC-BY-NC-SA-3.0-DE")),
    ("CC-BY-NC-SA-3.0-IGO", include!("text/CC-BY-NC-SA-3.0-IGO")),
    ("CC-BY-NC-SA-4.0", include!("text/CC-BY-NC-SA-4.0")),
    ("CC-BY-ND-1.0", include!("text/CC-BY-ND-1.0")),
    ("CC-BY-ND-2.0", include!("text/CC-BY-ND-2.0")),
    ("CC-BY-ND-2.5", include!("text/CC-BY-ND-2.5")),
    ("CC-BY-ND-3.0", include!("text/CC-BY-ND-3.0")),
    ("CC-BY-ND-3.0-DE", include!("text/CC-BY-ND-3.0-DE")),
    ("CC-BY-ND-4.0", include!("text/CC-BY-ND-4.0")),
    ("CC-BY-SA-1.0", include!("text/CC-BY-SA-1.0")),
    ("CC-BY-SA-2.0", include!("text/CC-BY-SA-2.0")),
    ("CC-BY-SA-2.0-UK", include!("text/CC-BY-SA-2.0-UK")),
    ("CC-BY-SA-2.1-JP", include!("text/CC-BY-SA-2.1-JP")),
    ("CC-BY-SA-2.5", include!("text/CC-BY-SA-2.5")),
    ("CC-BY-SA-3.0", include!("text/CC-BY-SA-3.0")),
    ("CC-BY-SA-3.0-AT", include!("text/CC-BY-SA-3.0-AT")),
    ("CC-BY-SA-3.0-DE", include!("text/CC-BY-SA-3.0-DE")),
    ("CC-BY-SA-4.0", include!("text/CC-BY-SA-4.0")),
    ("CC-PDDC", include!("text/CC-PDDC")),
    ("CC0-1.0", include!("text/CC0-1.0")),
    ("CDDL-1.0", include!("text/CDDL-1.0")),
    ("CDDL-1.1", include!("text/CDDL-1.1")),
    ("CDL-1.0", include!("text/CDL-1.0")),
    ("CDLA-Permissive-1.0", include!("text/CDLA-Permissive-1.0")),
    ("CDLA-Permissive-2.0", include!("text/CDLA-Permissive-2.0")),
    ("CDLA-Sharing-1.0", include!("text/CDLA-Sharing-1.0")),
    ("CECILL-1.0", include!("text/CECILL-1.0")),
    ("CECILL-1.1", include!("text/CECILL-1.1")),
    ("CECILL-2.0", include!("text/CECILL-2.0")),
    ("CECILL-2.1", include!("text/CECILL-2.1")),
    ("CECILL-B", include!("text/CECILL-B")),
    ("CECILL-C", include!("text/CECILL-C")),
    ("CERN-OHL-1.1", include!("text/CERN-OHL-1.1")),
    ("CERN-OHL-1.2", include!("text/CERN-OHL-1.2")),
    ("CERN-OHL-P-2.0", include!("text/CERN-OHL-P-2.0")),
    ("CERN-OHL-S-2.0", include!("text/CERN-OHL-S-2.0")),
    ("CERN-OHL-W-2.0", include!("text/CERN-OHL-W-2.0")),
    ("CNRI-Jython", include!("text/CNRI-Jython")),
    ("CNRI-Python", include!("text/CNRI-Python")),
    (
        "CNRI-Python-GPL-Compatible",
        include!("text/CNRI-Python-GPL-Compatible"),
    ),
    ("CPAL-1.0", include!("text/CPAL-1.0")),
    ("CPL-1.0", include!("text/CPL-1.0")),
    ("CPOL-1.02", include!("text/CPOL-1.02")),
    ("CUA-OPL-1.0", include!("text/CUA-OPL-1.0")),
    ("Caldera", include!("text/Caldera")),
    ("ClArtistic", include!("text/ClArtistic")),
    ("Condor-1.1", include!("text/Condor-1.1")),
    ("Crossword", include!("text/Crossword")),
    ("CrystalStacker", include!("text/CrystalStacker")),
    ("Cube", include!("text/Cube")),
    ("D-FSL-1.0", include!("text/D-FSL-1.0")),
    ("DOC", include!("text/DOC")),
    ("DRL-1.0", include!("text/DRL-1.0")),
    ("DSDP", include!("text/DSDP")),
    ("Dotseqn", include!("text/Dotseqn")),
    ("ECL-1.0", include!("text/ECL-1.0")),
    ("ECL-2.0", include!("text/ECL-2.0")),
    ("EFL-1.0", include!("text/EFL-1.0")),
    ("EFL-2.0", include!("text/EFL-2.0")),
    ("EPICS", include!("text/EPICS")),
    ("EPL-1.0", include!("text/EPL-1.0")),
    ("EPL-2.0", include!("text/EPL-2.0")),
    ("EUDatagrid", include!("text/EUDatagrid")),
    ("EUPL-1.0", include!("text/EUPL-1.0")),
    ("EUPL-1.1", include!("text/EUPL-1.1")),
    ("EUPL-1.2", include!("text/EUPL-1.2")),
    ("Entessa", include!("text/Entessa")),
    ("ErlPL-1.1", include!("text/ErlPL-1.1")),
    ("Eurosym", include!("text/Eurosym")),
    ("FSFAP", include!("text/FSFAP")),
    ("FSFUL", include!("text/FSFUL")),
    ("FSFULLR", include!("text/FSFULLR")),
    ("FTL", include!("text/FTL")),
    ("Fair", include!("text/Fair")),
    ("Frameworx-1.0", include!("text/Frameworx-1.0")),
    ("FreeBSD-DOC", include!("text/FreeBSD-DOC")),
    ("FreeImage", include!("text/FreeImage")),
    ("GD", include!("text/GD")),
    ("GFDL-1.1", include!("text/GFDL-1.1")),
    (
        "GFDL-1.1-invariants",
        include!("text/GFDL-1.1-invariants-only"),
    ),
    (
        "GFDL-1.1-invariants-only",
        include!("text/GFDL-1.1-invariants-only"),
    ),
    (
        "GFDL-1.1-invariants-or-later",
        include!("text/GFDL-1.1-invariants-or-later"),
    ),
    (
        "GFDL-1.1-no-invariants",
        include!("text/GFDL-1.1-no-invariants-only"),
    ),
    (
        "GFDL-1.1-no-invariants-only",
        include!("text/GFDL-1.1-no-invariants-only"),
    ),
    (
        "GFDL-1.1-no-invariants-or-later",
        include!("text/GFDL-1.1-no-invariants-or-later"),
    ),
    ("GFDL-1.1-only", include!("text/GFDL-1.1-only")),
    ("GFDL-1.1-or-later", include!("text/GFDL-1.1-or-later")),
    ("GFDL-1.2", include!("text/GFDL-1.2")),
    (
        "GFDL-1.2-invariants",
        include!("text/GFDL-1.2-invariants-only"),
    ),
    (
        "GFDL-1.2-invariants-only",
        include!("text/GFDL-1.2-invariants-only"),
    ),
    (
        "GFDL-1.2-invariants-or-later",
        include!("text/GFDL-1.2-invariants-or-later"),
    ),
    (
        "GFDL-1.2-no-invariants",
        include!("text/GFDL-1.2-no-invariants-only"),
    ),
    (
        "GFDL-1.2-no-invariants-only",
        include!("text/GFDL-1.2-no-invariants-only"),
    ),
    (
        "GFDL-1.2-no-invariants-or-later",
        include!("text/GFDL-1.2-no-invariants-or-later"),
    ),
    ("GFDL-1.2-only", include!("text/GFDL-1.2-only")),
    ("GFDL-1.2-or-later", include!("text/GFDL-1.2-or-later")),
    ("GFDL-1.3", include!("text/GFDL-1.3")),
    (
        "GFDL-1.3-invariants",
        include!("text/GFDL-1.3-invariants-only"),
    ),
    (
        "GFDL-1.3-invariants-only",
        include!("text/GFDL-1.3-invariants-only"),
    ),
    (
        "GFDL-1.3-invariants-or-later",
        include!("text/GFDL-1.3-invariants-or-later"),
    ),
    (
        "GFDL-1.3-no-invariants",
        include!("text/GFDL-1.3-no-invariants-only"),
    ),
    (
        "GFDL-1.3-no-invariants-only",
        include!("text/GFDL-1.3-no-invariants-only"),
    ),
    (
        "GFDL-1.3-no-invariants-or-later",
        include!("text/GFDL-1.3-no-invariants-or-later"),
    ),
    ("GFDL-1.3-only", include!("text/GFDL-1.3-only")),
    ("GFDL-1.3-or-later", include!("text/GFDL-1.3-or-later")),
    ("GL2PS", include!("text/GL2PS")),
    ("GLWTPL", include!("text/GLWTPL")),
    ("GPL-1.0", include!("text/GPL-1.0")),
    ("GPL-1.0+", include!("text/GPL-1.0+")),
    ("GPL-1.0-only", include!("text/GPL-1.0-only")),
    ("GPL-1.0-or-later", include!("text/GPL-1.0-or-later")),
    ("GPL-2.0", include!("text/GPL-2.0")),
    ("GPL-2.0+", include!("text/GPL-2.0+")),
    ("GPL-2.0-only", include!("text/GPL-2.0-only")),
    ("GPL-2.0-or-later", include!("text/GPL-2.0-or-later")),
    (
        "GPL-2.0-with-GCC-exception",
        include!("text/GPL-2.0-with-GCC-exception"),
    ),
    (
        "GPL-2.0-with-autoconf-exception",
        include!("text/GPL-2.0-with-autoconf-exception"),
    ),
    (
        "GPL-2.0-with-bison-exception",
        include!("text/GPL-2.0-with-bison-exception"),
    ),
    (
        "GPL-2.0-with-classpath-exception",
        include!("text/GPL-2.0-with-classpath-exception"),
    ),
    (
        "GPL-2.0-with-font-exception",
        include!("text/GPL-2.0-with-font-exception"),
    ),
    ("GPL-3.0", include!("text/GPL-3.0")),
    ("GPL-3.0+", include!("text/GPL-3.0+")),
    ("GPL-3.0-only", include!("text/GPL-3.0-only")),
    ("GPL-3.0-or-later", include!("text/GPL-3.0-or-later")),
    (
        "GPL-3.0-with-GCC-exception",
        include!("text/GPL-3.0-with-GCC-exception"),
    ),
    (
        "GPL-3.0-with-autoconf-exception",
        include!("text/GPL-3.0-with-autoconf-exception"),
    ),
    ("Giftware", include!("text/Giftware")),
    ("Glide", include!("text/Glide")),
    ("Glulxe", include!("text/Glulxe")),
    ("HPND", include!("text/HPND")),
    ("HPND-sell-variant", include!("text/HPND-sell-variant")),
    ("HTMLTIDY", include!("text/HTMLTIDY")),
    ("HaskellReport", include!("text/HaskellReport")),
    ("Hippocratic-2.1", include!("text/Hippocratic-2.1")),
    ("IBM-pibs", include!("text/IBM-pibs")),
    ("ICU", include!("text/ICU")),
    ("IJG", include!("text/IJG")),
    ("IPA", include!("text/IPA")),
    ("IPL-1.0", include!("text/IPL-1.0")),
    ("ISC", include!("text/ISC")),
    ("ImageMagick", include!("text/ImageMagick")),
    ("Imlib2", include!("text/Imlib2")),
    ("Info-ZIP", include!("text/Info-ZIP")),
    ("Intel", include!("text/Intel")),
    ("Intel-ACPI", include!("text/Intel-ACPI")),
    ("Interbase-1.0", include!("text/Interbase-1.0")),
    ("JPNIC", include!("text/JPNIC")),
    ("JSON", include!("text/JSON")),
    ("JasPer-2.0", include!("text/JasPer-2.0")),
    ("LAL-1.2", include!("text/LAL-1.2")),
    ("LAL-1.3", include!("text/LAL-1.3")),
    ("LGPL-2.0", include!("text/LGPL-2.0")),
    ("LGPL-2.0+", include!("text/LGPL-2.0+")),
    ("LGPL-2.0-only", include!("text/LGPL-2.0-only")),
    ("LGPL-2.0-or-later", include!("text/LGPL-2.0-or-later")),
    ("LGPL-2.1", include!("text/LGPL-2.1")),
    ("LGPL-2.1+", include!("text/LGPL-2.1+")),
    ("LGPL-2.1-only", include!("text/LGPL-2.1-only")),
    ("LGPL-2.1-or-later", include!("text/LGPL-2.1-or-later")),
    ("LGPL-3.0", include!("text/LGPL-3.0")),
    ("LGPL-3.0+", include!("text/LGPL-3.0+")),
    ("LGPL-3.0-only", include!("text/LGPL-3.0-only")),
    ("LGPL-3.0-or-later", include!("text/LGPL-3.0-or-later")),
    ("LGPLLR", include!("text/LGPLLR")),
    ("LPL-1.0", include!("text/LPL-1.0")),
    ("LPL-1.02", include!("text/LPL-1.02")),
    ("LPPL-1.0", include!("text/LPPL-1.0")),
    ("LPPL-1.1", include!("text/LPPL-1.1")),
    ("LPPL-1.2", include!("text/LPPL-1.2")),
    ("LPPL-1.3a", include!("text/LPPL-1.3a")),
    ("LPPL-1.3c", include!("text/LPPL-1.3c")),
    ("Latex2e", include!("text/Latex2e")),
    ("Leptonica", include!("text/Leptonica")),
    ("LiLiQ-P-1.1", include!("text/LiLiQ-P-1.1")),
    ("LiLiQ-R-1.1", include!("text/LiLiQ-R-1.1")),
    ("LiLiQ-Rplus-1.1", include!("text/LiLiQ-Rplus-1.1")),
    ("Libpng", include!("text/Libpng")),
    ("Linux-OpenIB", include!("text/Linux-OpenIB")),
    ("MIT", include!("text/MIT")),
    ("MIT-0", include!("text/MIT-0")),
    ("MIT-CMU", include!("text/MIT-CMU")),
    ("MIT-Modern-Variant", include!("text/MIT-Modern-Variant")),
    ("MIT-advertising", include!("text/MIT-advertising")),
    ("MIT-enna", include!("text/MIT-enna")),
    ("MIT-feh", include!("text/MIT-feh")),
    ("MIT-open-group", include!("text/MIT-open-group")),
    ("MITNFA", include!("text/MITNFA")),
    ("MPL-1.0", include!("text/MPL-1.0")),
    ("MPL-1.1", include!("text/MPL-1.1")),
    ("MPL-2.0", include!("text/MPL-2.0")),
    (
        "MPL-2.0-no-copyleft-exception",
        include!("text/MPL-2.0-no-copyleft-exception"),
    ),
    ("MS-PL", include!("text/MS-PL")),
    ("MS-RL", include!("text/MS-RL")),
    ("MTLL", include!("text/MTLL")),
    ("MakeIndex", include!("text/MakeIndex")),
    ("MirOS", include!("text/MirOS")),
    ("Motosoto", include!("text/Motosoto")),
    ("MulanPSL-1.0", include!("text/MulanPSL-1.0")),
    ("MulanPSL-2.0", include!("text/MulanPSL-2.0")),
    ("Multics", include!("text/Multics")),
    ("Mup", include!("text/Mup")),
    ("NAIST-2003", include!("text/NAIST-2003")),
    ("NASA-1.3", include!("text/NASA-1.3")),
    ("NBPL-1.0", include!("text/NBPL-1.0")),
    ("NCGL-UK-2.0", include!("text/NCGL-UK-2.0")),
    ("NCSA", include!("text/NCSA")),
    ("NGPL", include!("text/NGPL")),
    ("NIST-PD", include!("text/NIST-PD")),
    ("NIST-PD-fallback", include!("text/NIST-PD-fallback")),
    ("NLOD-1.0", include!("text/NLOD-1.0")),
    ("NLOD-2.0", include!("text/NLOD-2.0")),
    ("NLPL", include!("text/NLPL")),
    ("NOASSERTION", ""),
    ("NOSL", include!("text/NOSL")),
    ("NPL-1.0", include!("text/NPL-1.0")),
    ("NPL-1.1", include!("text/NPL-1.1")),
    ("NPOSL-3.0", include!("text/NPOSL-3.0")),
    ("NRL", include!("text/NRL")),
    ("NTP", include!("text/NTP")),
    ("NTP-0", include!("text/NTP-0")),
    ("Naumen", include!("text/Naumen")),
    ("Net-SNMP", include!("text/Net-SNMP")),
    ("NetCDF", include!("text/NetCDF")),
    ("Newsletr", include!("text/Newsletr")),
    ("Nokia", include!("text/Nokia")),
    ("Noweb", include!("text/Noweb")),
    ("Nunit", include!("text/Nunit")),
    ("O-UDA-1.0", include!("text/O-UDA-1.0")),
    ("OCCT-PL", include!("text/OCCT-PL")),
    ("OCLC-2.0", include!("text/OCLC-2.0")),
    ("ODC-By-1.0", include!("text/ODC-By-1.0")),
    ("ODbL-1.0", include!("text/ODbL-1.0")),
    ("OFL-1.0", include!("text/OFL-1.0")),
    ("OFL-1.0-RFN", include!("text/OFL-1.0-RFN")),
    ("OFL-1.0-no-RFN", include!("text/OFL-1.0-no-RFN")),
    ("OFL-1.1", include!("text/OFL-1.1")),
    ("OFL-1.1-RFN", include!("text/OFL-1.1-RFN")),
    ("OFL-1.1-no-RFN", include!("text/OFL-1.1-no-RFN")),
    ("OGC-1.0", include!("text/OGC-1.0")),
    ("OGDL-Taiwan-1.0", include!("text/OGDL-Taiwan-1.0")),
    ("OGL-Canada-2.0", include!("text/OGL-Canada-2.0")),
    ("OGL-UK-1.0", include!("text/OGL-UK-1.0")),
    ("OGL-UK-2.0", include!("text/OGL-UK-2.0")),
    ("OGL-UK-3.0", include!("text/OGL-UK-3.0")),
    ("OGTSL", include!("text/OGTSL")),
    ("OLDAP-1.1", include!("text/OLDAP-1.1")),
    ("OLDAP-1.2", include!("text/OLDAP-1.2")),
    ("OLDAP-1.3", include!("text/OLDAP-1.3")),
    ("OLDAP-1.4", include!("text/OLDAP-1.4")),
    ("OLDAP-2.0", include!("text/OLDAP-2.0")),
    ("OLDAP-2.0.1", include!("text/OLDAP-2.0.1")),
    ("OLDAP-2.1", include!("text/OLDAP-2.1")),
    ("OLDAP-2.2", include!("text/OLDAP-2.2")),
    ("OLDAP-2.2.1", include!("text/OLDAP-2.2.1")),
    ("OLDAP-2.2.2", include!("text/OLDAP-2.2.2")),
    ("OLDAP-2.3", include!("text/OLDAP-2.3")),
    ("OLDAP-2.4", include!("text/OLDAP-2.4")),
    ("OLDAP-2.5", include!("text/OLDAP-2.5")),
    ("OLDAP-2.6", include!("text/OLDAP-2.6")),
    ("OLDAP-2.7", include!("text/OLDAP-2.7")),
    ("OLDAP-2.8", include!("text/OLDAP-2.8")),
    ("OML", include!("text/OML")),
    ("OPL-1.0", include!("text/OPL-1.0")),
    ("OPUBL-1.0", include!("text/OPUBL-1.0")),
    ("OSET-PL-2.1", include!("text/OSET-PL-2.1")),
    ("OSL-1.0", include!("text/OSL-1.0")),
    ("OSL-1.1", include!("text/OSL-1.1")),
    ("OSL-2.0", include!("text/OSL-2.0")),
    ("OSL-2.1", include!("text/OSL-2.1")),
    ("OSL-3.0", include!("text/OSL-3.0")),
    ("OpenSSL", include!("text/OpenSSL")),
    ("PDDL-1.0", include!("text/PDDL-1.0")),
    ("PHP-3.0", include!("text/PHP-3.0")),
    ("PHP-3.01", include!("text/PHP-3.01")),
    ("PSF-2.0", include!("text/PSF-2.0")),
    ("Parity-6.0.0", include!("text/Parity-6.0.0")),
    ("Parity-7.0.0", include!("text/Parity-7.0.0")),
    ("Plexus", include!("text/Plexus")),
    (
        "PolyForm-Noncommercial-1.0.0",
        include!("text/PolyForm-Noncommercial-1.0.0"),
    ),
    (
        "PolyForm-Small-Business-1.0.0",
        include!("text/PolyForm-Small-Business-1.0.0"),
    ),
    ("PostgreSQL", include!("text/PostgreSQL")),
    ("Python-2.0", include!("text/Python-2.0")),
    ("QPL-1.0", include!("text/QPL-1.0")),
    ("Qhull", include!("text/Qhull")),
    ("RHeCos-1.1", include!("text/RHeCos-1.1")),
    ("RPL-1.1", include!("text/RPL-1.1")),
    ("RPL-1.5", include!("text/RPL-1.5")),
    ("RPSL-1.0", include!("text/RPSL-1.0")),
    ("RSA-MD", include!("text/RSA-MD")),
    ("RSCPL", include!("text/RSCPL")),
    ("Rdisc", include!("text/Rdisc")),
    ("Ruby", include!("text/Ruby")),
    ("SAX-PD", include!("text/SAX-PD")),
    ("SCEA", include!("text/SCEA")),
    ("SGI-B-1.0", include!("text/SGI-B-1.0")),
    ("SGI-B-1.1", include!("text/SGI-B-1.1")),
    ("SGI-B-2.0", include!("text/SGI-B-2.0")),
    ("SHL-0.5", include!("text/SHL-0.5")),
    ("SHL-0.51", include!("text/SHL-0.51")),
    ("SISSL", include!("text/SISSL")),
    ("SISSL-1.2", include!("text/SISSL-1.2")),
    ("SMLNJ", include!("text/SMLNJ")),
    ("SMPPL", include!("text/SMPPL")),
    ("SNIA", include!("text/SNIA")),
    ("SPL-1.0", include!("text/SPL-1.0")),
    ("SSH-OpenSSH", include!("text/SSH-OpenSSH")),
    ("SSH-short", include!("text/SSH-short")),
    ("SSPL-1.0", include!("text/SSPL-1.0")),
    ("SWL", include!("text/SWL")),
    ("Saxpath", include!("text/Saxpath")),
    ("Sendmail", include!("text/Sendmail")),
    ("Sendmail-8.23", include!("text/Sendmail-8.23")),
    ("SimPL-2.0", include!("text/SimPL-2.0")),
    ("Sleepycat", include!("text/Sleepycat")),
    ("Spencer-86", include!("text/Spencer-86")),
    ("Spencer-94", include!("text/Spencer-94")),
    ("Spencer-99", include!("text/Spencer-99")),
    ("StandardML-NJ", include!("text/StandardML-NJ")),
    ("SugarCRM-1.1.3", include!("text/SugarCRM-1.1.3")),
    ("TAPR-OHL-1.0", include!("text/TAPR-OHL-1.0")),
    ("TCL", include!("text/TCL")),
    ("TCP-wrappers", include!("text/TCP-wrappers")),
    ("TMate", include!("text/TMate")),
    ("TORQUE-1.1", include!("text/TORQUE-1.1")),
    ("TOSL", include!("text/TOSL")),
    ("TU-Berlin-1.0", include!("text/TU-Berlin-1.0")),
    ("TU-Berlin-2.0", include!("text/TU-Berlin-2.0")),
    ("UCL-1.0", include!("text/UCL-1.0")),
    ("UPL-1.0", include!("text/UPL-1.0")),
    ("Unicode-DFS-2015", include!("text/Unicode-DFS-2015")),
    ("Unicode-DFS-2016", include!("text/Unicode-DFS-2016")),
    ("Unicode-TOU", include!("text/Unicode-TOU")),
    ("Unlicense", include!("text/Unlicense")),
    ("VOSTROM", include!("text/VOSTROM")),
    ("VSL-1.0", include!("text/VSL-1.0")),
    ("Vim", include!("text/Vim")),
    ("W3C", include!("text/W3C")),
    ("W3C-19980720", include!("text/W3C-19980720")),
    ("W3C-20150513", include!("text/W3C-20150513")),
    ("WTFPL", include!("text/WTFPL")),
    ("Watcom-1.0", include!("text/Watcom-1.0")),
    ("Wsuipa", include!("text/Wsuipa")),
    ("X11", include!("text/X11")),
    ("XFree86-1.1", include!("text/XFree86-1.1")),
    ("XSkat", include!("text/XSkat")),
    ("Xerox", include!("text/Xerox")),
    ("Xnet", include!("text/Xnet")),
    ("YPL-1.0", include!("text/YPL-1.0")),
    ("YPL-1.1", include!("text/YPL-1.1")),
    ("ZPL-1.1", include!("text/ZPL-1.1")),
    ("ZPL-2.0", include!("text/ZPL-2.0")),
    ("ZPL-2.1", include!("text/ZPL-2.1")),
    ("Zed", include!("text/Zed")),
    ("Zend-2.0", include!("text/Zend-2.0")),
    ("Zimbra-1.3", include!("text/Zimbra-1.3")),
    ("Zimbra-1.4", include!("text/Zimbra-1.4")),
    ("Zlib", include!("text/Zlib")),
    ("blessing", include!("text/blessing")),
    ("bzip2-1.0.5", include!("text/bzip2-1.0.5")),
    ("bzip2-1.0.6", include!("text/bzip2-1.0.6")),
    ("copyleft-next-0.3.0", include!("text/copyleft-next-0.3.0")),
    ("copyleft-next-0.3.1", include!("text/copyleft-next-0.3.1")),
    ("curl", include!("text/curl")),
    ("diffmark", include!("text/diffmark")),
    ("dvipdfm", include!("text/dvipdfm")),
    ("eCos-2.0", include!("text/eCos-2.0")),
    ("eGenix", include!("text/eGenix")),
    ("etalab-2.0", include!("text/etalab-2.0")),
    ("gSOAP-1.3b", include!("text/gSOAP-1.3b")),
    ("gnuplot", include!("text/gnuplot")),
    ("iMatix", include!("text/iMatix")),
    ("libpng-2.0", include!("text/libpng-2.0")),
    ("libselinux-1.0", include!("text/libselinux-1.0")),
    ("libtiff", include!("text/libtiff")),
    ("mpich2", include!("text/mpich2")),
    ("psfrag", include!("text/psfrag")),
    ("psutils", include!("text/psutils")),
    ("wxWindows", include!("text/wxWindows")),
    ("xinetd", include!("text/xinetd")),
    ("xpp", include!("text/xpp")),
    (
        "zlib-acknowledgement",
        include!("text/zlib-acknowledgement"),
    ),
];
